version: '3'

services:
  coreondocker:
    image: coreondocker
    build:
      context: .
      dockerfile: coreondocker/Dockerfile
    networks:
      - overlay
    depends_on:
      - "postgres-db"

  postgres-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - overlay


volumes:
  pgdata:

networks:
  overlay: